# This file is used to extend the standarrd rust-driver-makefile to build official sample drivers. See examples at https://github.com/microsoft/Windows-rust-drivers-samples
# Using this file requires extending both the standard makefile and this makefile in order, as follows:
# extend = [ { path =  "target/rust-driver-makefile.toml" }, { path = "target/rust-driver-sample-makefile.toml" } ]

[tasks.infverif]
dependencies = ["wdk-samples-setup", "stampinf"]
condition = { env_not_set = ["WDK_INF_USING_NEW_VERSION"] }
