# This file is used to extend the standard rust-driver-makefile to build official sample drivers. See examples at https://github.com/microsoft/Windows-rust-drivers-samples
# Using this file requires extending both the standard makefile and this makefile in order, as follows:
# extend = [ { path =  "target/rust-driver-makefile.toml" }, { path = "target/rust-driver-sample-makefile.toml" } ]

[tasks.wdk-samples-setup]
private = true
dependencies = ["wdk-build-init"]
install_crate = { crate_name = "rust-script", min_version = "0.30.0" }
plugin = "rust-env-update"
script_runner = "@rust"
script = '''
//! ```cargo
//! [dependencies]
//! wdk-build = { path = ".", version = "0.2.0" }
//! ```
#![allow(unused_doc_comments)]
let env_string = std::env::var_os(wdk_build::cargo_make::WDK_VERSION_ENV_VAR)
    .map_or_else(
        || panic!("Couldn't read WDK build version that should have been set in init"),
        |os_env_string| os_env_string.to_string_lossy().into_owned(),
    );
wdk_build::cargo_make::setup_infverif_for_samples(env_string)?;
'''

[tasks.infverif]
dependencies = ["wdk-samples-setup", "stampinf"]
install_crate = { crate_name = "rust-script", min_version = "0.30.0" }
script_runner = "@rust"
condition_script = '''
//! ```cargo
//! [dependencies]
//! wdk-build = { path = ".", version = "0.2.0" }
//! ```
#![allow(unused_doc_comments)]

// This range is inclusive of 25798. FIXME: update with range end after /sample flag is added to InfVerif CLI
const MISSING_SAMPLE_FLAG_WDK_BUILD_NUMBER_RANGE: u32 = 25798..;

std::panic::catch_unwind(|| {
	let wdk_version = std::env::var(wdk_build::cargo_make::WDK_VERSION_ENV_VAR).expect("WDK_BUILD_DETECTED_VERSION should always be set by wdk-build-init cargo make task");
	let wdk_build_number = wdk_build::utils::get_wdk_build_number(wdk_version);

	if MISSING_SAMPLE_FLAG_WDK_BUILD_NUMBER_RANGE.contains(&wdk_build_number) {
		// cargo_make will interpret returning an error from the rust-script condition_script as skipping the task
		return Err(format!("Skipping InfVerif. InfVerif in WDK Build {version} is bugged and does not contain the /samples flag.").into());
	}
	Ok(())
}).unwrap_or_else(|_|{
	// panic contents would have already been printed to console
	eprintln!("condition_script for infverif task panicked while executing. Defaulting to running inverif task.");
	Ok(())
})?
'''